addpath(genpath('.'))

% SPM12 must also be in the path

fsthalconn( ...
	'out_dir','../OUTPUTS', ...
	'subject_dir','../INPUTS/SUBJECT', ...
	'roiinfo_csv','CombinedFreesurferLabels_reorg.csv', ...
	'removegm_niigz','../INPUTS/filtered_removegm_noscrub_nadfmri.nii.gz', ...
	'keepgm_niigz','../INPUTS/filtered_keepgm_noscrub_nadfmri.nii.gz', ...
	'wremovegm_niigz','../INPUTS/filtered_removegm_noscrub_wadfmri.nii.gz', ...
	'wkeepgm_niigz','../INPUTS/filtered_keepgm_noscrub_wadfmri.nii.gz', ...
	'wedge_niigz','../INPUTS/redge_wgray.nii.gz', ...
	'wbrainmask_niigz','../INPUTS/rwmask.nii.gz', ...
	'wmeanfmri_niigz','../INPUTS/wmeanadfmri.nii.gz', ...
	't1_niigz','../INPUTS/mt1.nii.gz', ...
	'wt1_niigz','../INPUTS/wmt1.nii.gz', ...
	'fwhm','6', ...
	'project','UNK_PROJ', ...
	'subject','UNK_SUBJ', ...
	'session','UNK_SESS', ...
	'scan','UNK_SCAN', ...
	'magick_path','/usr/local/bin' ...
	);
