addpath(genpath('.'))

% SPM12 must also be in the path


% We need full pathspecs here, no relative paths
fsthalconn( ...
	'out_dir','/repo/fslthalconn/OUTPUTS', ...
	'subject_dir','/repo/fslthalconn/INPUTS/SUBJECT', ...
	'roiinfo_csv','CombinedFreesurferLabels_reorg.csv', ...
	'removegm_niigz','/repo/fslthalconn/INPUTS/filtered_removegm_noscrub_nadfmri.nii.gz', ...
	'keepgm_niigz','/repo/fslthalconn/INPUTS/filtered_keepgm_noscrub_nadfmri.nii.gz', ...
	'wremovegm_niigz','/repo/fslthalconn/INPUTS/filtered_removegm_noscrub_wadfmri.nii.gz', ...
	'wkeepgm_niigz','/repo/fslthalconn/INPUTS/filtered_keepgm_noscrub_wadfmri.nii.gz', ...
	'wedge_niigz','/repo/fslthalconn/INPUTS/redge_wgray.nii.gz', ...
	'wbrainmask_niigz','/repo/fslthalconn/INPUTS/rwmask.nii.gz', ...
	'wmeanfmri_niigz','/repo/fslthalconn/INPUTS/wmeanadfmri.nii.gz', ...
	't1_niigz','/repo/fslthalconn/INPUTS/mt1.nii.gz', ...
	'wt1_niigz','/repo/fslthalconn/INPUTS/wmt1.nii.gz', ...
	'fwhm','6', ...
	'project','UNK_PROJ', ...
	'subject','UNK_SUBJ', ...
	'session','UNK_SESS', ...
	'scan','UNK_SCAN', ...
	'magick_path','/usr/local/bin' ...
	);
